server:
  port: 80

  # ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: cloud-consumer-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}